config/routes.rb
Rails.application.routes.draw do

	get '/', to: 'site#home'

	get '/buy_pages', to: 'site#buy_pages'

	get '/:brand/models', to: 'site#models'

	devise_for :users

	resources :users, only: [:index, :show]
	
	resources :reviews, except: [:show]

	post '/get_brand_models', to: 'cars#get_brand_models'

	get '/reviews/:search', to: 'reviews#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :model_year, presence: true, 
  					numericality: { only_integer: true, grater_than: 1920 }
  validates :kilometers, presence: true,
  					numericality: { only_integer: true }
  validates :fuel_type, presence: true
  validates :engine_type, presence: true
  validates :horsepower, presence: true, 
  					numericality: { only_integer: true }
  validates :comment, presence: true
  validates :punctuation, presence: true, 
  					numericality: { only_integer: true, less_than_or_equal_to: 5 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_many :reviews
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
  has_attached_file :profile_picture, styles: { medium: "300x300>", thumb: "300x300>" }, default_url: "/assets/Profile/missing.png"
  validates_attachment_content_type :profile_picture, content_type: /\Aimage\/.*\z/
  validates_presence_of :password, on: :create
  validates :nickname, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  
  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile_picture])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :profile_picture])
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

	def get_brand_models

		@cars = Car.where(brand: params[:brand])
		
		model_array = []
		@cars.each do |car|
			model_array.push({car_model: "#{car.model}", car_id: "#{car.id}" })
		end
		render :json => model_array
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

	def index
    if params[:search].present?
    	if params[:search].class != String
      	cars = Car.where("lower(model) LIKE ?", "%#{params[:search][:keywords]}%".downcase)
      else
      	cars = Car.where("lower(model) LIKE ?", "%#{params[:search]}%".downcase)
      end

      if (cars.length == 0)
      	render 'model_not_found'
      else
    		@reviews = cars.reduce([]){|sum,item| sum+item.reviews}
    		
    		if (@reviews.length == 0)
    			render 'no_model_reviews'
    		end
    	end
    else
      @reviews = Review.all.order("updated_at DESC").paginate(:page => params[:page], :per_page => 10)
    end
	end

	def new
		@user = User.find(current_user)
		@review = Review.new
		@cars = Car.all
	end
	
	def create
		@user = User.find(current_user)
		@review = @user.reviews.new(review_params)
		
		if @review.save
			redirect_to user_path(current_user.id)
		else
			render 'new'
		end
	end

	def edit
		@review = Review.find(params[:id])
		@user = current_user
	end

	def update
		@review = Review.find_by_id(params[:id])

		if @review.update(review_params)
			redirect_to "/users/#{@review.user_id}"
		else
			render 'edit'
		end
	end

	def destroy
		@review = Review.find(params[:id])
		@review.destroy
		redirect_to user_path(current_user.id)
	end

	private

	def review_params
      params.require(:review).permit(:model_year, :kilometers, :fuel_type, :engine_type, :horsepower, :user_id, :car_id, :comment, :punctuation)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	skip_before_action :authenticate_user!, only: :home
	
	def home
		@cars = Car.all
	end

	def buy_pages
		@cars = Car.all
	end

	def models
		@cars = Car.where(brand: params[:brand])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		if params[:search].present?
      @users = User.where("lower(nickname) LIKE ?", "%#{params[:search][:keywords]}%".downcase)
    else
      @users = User.all
    end
	end

	def show
		@user = User.find(params[:id])
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		
		respond_to do |format|
      		format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
    	end
	end

	private
	
	def user_params
      params.require(:user).permit(:profile_picture, :nickname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

	def punctuation_stars(review)
		@stars = []
		 @review.punctuation.times do 
				@stars << "<span class='glyphicon glyphicon-star' aria-hidden='true'></span>"
			end
			(5-@review.punctuation).times do
				@stars << "<span class='glyphicon glyphicon-star-empty' aria-hidden='true'></span>"
			end
			@stars.join().html_safe
	end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarReviews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-faded">
    <img src="/assets/Logomakr_1CZBlN.png">

      <ul class="nav navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', '/', :id => "nav-link" %>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to 'Profile', user_path(current_user.id), :id => "nav-link" %>
          <% else %>
            <%= link_to 'Profile', '/users', :id => "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', '/users', :id => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Reviews', '/reviews', :id => "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Buy pages', '/buy_pages', :id => "nav-link" %>
        </li>
      </ul>
        <div class="user-actions">

      <% if user_signed_in? %>
          Welcome <%= current_user.nickname %>,
          <%= link_to destroy_user_session_path, method: 'DELETE' do %>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Logout
          <% end %>
          <% else %>
            <%= link_to new_user_session_path, method: 'GET' do %> 
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Login |
            <% end %>
          <%= link_to 'Sign up', new_user_registration_path, method: 'GET' %> 
      <% end %>
        </div>
      

    </nav>
    
    <div class="container" id="container">

      <%= yield %>
    </div>
    <footer><p class="text-center">Car Reviews by: Sergi Fraiz Garcia</p></footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for (@review) , html: { class: 'form-horizontal'} do |f| %>
  <fieldset>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <strong><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</strong>

        <ul>
          <% @review.errors.full_messages.each do |message| %>
          <li><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span> <%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :brand, class: 'col-lg-2 control-label'%>
      <div class="col-lg-10">
        
        <% if @review.id %>
          <% car_selected = f.object.car.brand %>
        <% else %>
          <% car_selected = "" %>
        <%end%>
        
        <%= select_tag 'brand', options_for_select(Car.all.pluck(:brand).uniq { |brand| brand }, :selected => car_selected), class: 'form-control js-select-brand' %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :model, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.select 'car_id', options_for_select( Car.all.collect { |u| [u.model, u.id] }, :selected => f.object.car_id), {}, class: 'form-control js-model' %>
      </div>
    </div>
        
    <div class="form-group">
      <%= f.label :model_year, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field :model_year, autofocus: true, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :kilometers, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field :kilometers, class: 'form-control' %>
       </div>
    </div>
    
    <div class="form-group">
      <%= f.label :fuel_type, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.select 'fuel_type', options_for_select(["Gasoline","Diesel", "Hybrid", "Electric"], :selected => f.object.fuel_type), {},class: 'form-control' %>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :engine_type, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field :engine_type, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :horsepower, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field :horsepower, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :punctuation, class: 'col-lg-2 control-label' %>
      <div class="col-lg-10">
        <%= f.text_field :punctuation, class: 'form-control' %> <i>(number from 0 to 5)</i>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :comment, class: 'col-lg-2 control-label' %><br>
      <div class="col-lg-10">
        <%= f.text_area :comment, class: 'form-control' %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.button class: 'btn btn-primary btn-sm' %>

        <%= link_to 'Cancel', user_path(current_user), class: "btn btn-primary btn-sm" %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/reviews/_paginate.html.erb
<% if @reviews.length >= 3 %>
	<%= will_paginate @reviews %>
<% end %>

app/views/reviews/_print-reviews.html.erb
<li class="review-list">
	<div class="row review">
		<div class="col-md-3">
			<img src="/assets/Models/<%= @review.car.model_photo %>" alt="">
		</div>
		<div class="col-md-3">
			<em>By:</em> <%= link_to user_path(@review.user.id), method: 'GET' do %>
			<%= @review.user.nickname %>
			<% end %><br>
			<em>Brand:</em> <%= @review.car.brand %><br>
			<em>Fuel type:</em> <%= @review.fuel_type %>
		</div>
		<div class="col-md-3">
			<em>Car year:</em> <%= @review.model_year %><br>
			<em>Model:</em> <%= @review.car.model %><br>
			<em>Engine type:</em> <%= @review.engine_type %>
		</div>
		<div class="col-md-3">
			<%= punctuation_stars(@review) %> <br>
			<em>kilometers:</em> <%= @review.kilometers %> km<br>
			<em>Horsepower:</em> <%= @review.horsepower %> hp<br><br>
		</div>
			<div class="col-md-12">
				<em>Comment:</em><br>
			<div class="review-comment">	
				<%= @review.comment %>
			</div>
		</div>
	</div>
	<% if (@user && current_user.id == @user.id) || (current_user.id == @review.user.id) %>
		<%= link_to edit_review_path(@review.id),:class => 'btn btn-primary btn-xs', method: 'GET' do %> 
 			Edit <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
 		<% end %>
		<%= link_to review_path(@review.id), :class => 'btn btn-primary btn-xs', method: :delete, data: { confirm: 'Are you sure?' } do %> 
 			Delete <span class="glyphicon glyphicon-trash" aria-hidden="true"></span><br>
		<% end %>
	<% end %>
</li>

app/views/reviews/edit.html.erb
<h1><p class="text-center">Edit Review</p></h1>

<%= render "form" %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<%= form_for(:search, url: reviews_path, html: { role: 'search', method: 'GET'}) do |f| %>  
    <%= f.text_field :keywords, {placeholder: "model"} %>
    <%= f.button "Search", class: 'btn btn-primary btn-xs' %>
<% end %>

<%= render "paginate" %>

<ul>
	<% @reviews.each do |review| %>
		<% @review = review %> 
		<%= render "print-reviews" %>
	<% end %>
</ul>

<%= render "paginate" %>

app/views/reviews/model_not_found.html.erb
<div class="alert alert-dismissible alert-warning">
	<h2 class="not-found">MODEL NOT FOUND</h2><br>


	<%= link_to reviews_path, :class => 'back-search btn btn-primary btn-sm',  method: 'GET' do %> 
		Back 
	<% end %>
</div>

app/views/reviews/new.html.erb
<h1><p class="text-center">New Review</p></h1>

<%= render "form" %>

app/views/reviews/no_model_reviews.html.erb
<div class="alert alert-dismissible alert-warning">
  <h2 class="not-found">Sorry!<br> No reviews have been made for this model yet</h2><br>

<%= link_to reviews_path, :class => 'back-search btn btn-primary btn-sm',  method: 'GET' do %> 
	Back 
<% end %>
</div>

app/views/site/buy_pages.html.erb
<h2>Official websites:</h2><br>


<ul class="row brands-list">
	<% @cars.pluck(:brand, :web).uniq.each do |brand| %>

<li class="col-sm-4">
	 <div class="thumbnail">
	 <img src="/assets/Brands/<%= brand[0]+'.jpg'%>" alt="">
      <div class="caption">
        <p><a href="<%=brand[1]%>" class="btn btn-primary" role="button">Visit website</a> </p>
      </div>
    </div>
</li>
	<% end %>

</ul>

<h2>Other websites:</h2><br>
<ul class="row brands-list">
	<li class="col-sm-4">
		 <div class="thumbnail">
		 <img src="/assets/Websites/Coches-net.jpg" alt="">
	      <div class="caption">
	        <p><a href="http://www.coches.net/" class="btn btn-primary" role="button">Visit website</a> </p>
	      </div>
	    </div>
	</li>
	<li class="col-sm-4">
		 <div class="thumbnail">
		 <img src="/assets/Websites/autoscout24.jpg" alt="">
	      <div class="caption">
	        <p><a href="https://www.autoscout24.es/" class="btn btn-primary" role="button">Visit website</a> </p>
	      </div>
	    </div>
	</li>
	<li class="col-sm-4">
		 <div class="thumbnail">
		 <img src="/assets/Websites/coches.png" alt="">
	      <div class="caption">
	        <p><a href="http://www.coches.com/" class="btn btn-primary" role="button">Visit website</a> </p>
	      </div>
	    </div>
	</li>
	<li class="col-sm-4">
		 <div class="thumbnail">
		 <img src="/assets/Websites/autocasion.jpg" alt="">
	      <div class="caption">
	        <p><a href="http://www.autocasion.com/" class="btn btn-primary" role="button">Visit website</a> </p>
	      </div>
	    </div>
	</li>
	<li class="col-sm-4">
		 <div class="thumbnail">
		 <img src="/assets/Websites/vibbo.jpg" alt="">
	      <div class="caption">
	        <p><a href="http://www.vibbo.com/motor-de-segunda-mano/" class="btn btn-primary" role="button">Visit website</a> </p>
	      </div>
	    </div>
	</li>
	<li class="col-sm-4">
		 <div class="thumbnail">
		 <img src="/assets/Websites/wallapop.jpg" alt="">
	      <div class="caption">
	        <p><a href="http://es.wallapop.com/list/coches-y-motos" class="btn btn-primary" role="button">Visit website</a> </p>
	      </div>
	    </div>
	</li>
</ul>

app/views/site/home.html.erb
<h2 class="text-center">Choose the brand of the review you want to see!</h2>

<div class="row all_brands">
	<% @cars.pluck(:brand).uniq.each do |brand| %>
		<div class="col-sm-2 brand">
			<a href="<%= '/'+brand+'/models' %>"><img src="/assets/Brands/<%= brand+'.jpg' %>"></a><br>
		</div>		
	<% end %>
</div>

app/views/site/models.html.erb
<h2 class="text-center">Choose the model of the review you want to see!</h2>

<div class="row all_models">
	<% @cars.each do |car| %>
		<div class="col-sm-2 model">	
			<a href="/reviews/<%= car.model %>"><img src="/assets/Models/<%= car.model_photo %>"><br>
			<p class="text-center"><%= car.model %></p></a>
		</div>		
	<% end %>
	<div class="col-sm-12 back">
	<%= link_to '/', :class => 'back-search btn btn-primary btn-sm',  method: 'GET' do %> 
		Back 
	<% end %>
	</div>
</div>

app/views/users/_no_users_found.html.erb
<h3>No users found containing these characters in their nickname</h3>

app/views/users/index.html.erb
<h1>Users</h1>

<%= form_for(:search, url: users_path, html: { role: 'search', method: 'GET'}) do |f| %>  
    <%= f.text_field :keywords, {placeholder: "nickname"} %>
    <%= f.button "Search", class: 'btn btn-primary btn-xs' %>
<% end %>

<% if @users[0].present? == false %>
	<%= render "no_users_found" %>
<% else %>
	<ul class="users-list">
		<% @users.sort_by(&:nickname).each do |user| %>
		<li>
			<%= image_tag user.profile_picture.url(:thumb) %> <%= user.nickname %> - <%= link_to 'Profile', user_path(user.id) %>
		</li>
		<% end %>
	</ul>
<% end %>

app/views/users/show.html.erb
<div class="profile-header">	
	<h1><%= image_tag @user.profile_picture.url(:medium) %> <%= @user.nickname %></h1>

	<% if current_user.id == @user.id %>
		<%= link_to edit_user_registration_path, :class => 'btn btn-primary btn-xs', method: 'GET' do %> 
	    Edit <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
	  <% end %>
		<%= link_to "/users/#{@user.id}", :class => 'btn btn-primary btn-xs', method: :delete, data: { confirm: 'Are you sure?' } do %> 
	    Delete <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
	  <% end %><br><br>
		<%= link_to new_review_path, :class => 'btn btn-primary btn-sm',  method: 'GET' do %> 
	    New Review <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
	  <% end %>
	<% end %><br>
</div>

<ul>
	<% @user.reviews.order("updated_at DESC").each do |review| %>
		<% @review = review %> 
		<%= render "reviews/print-reviews" %>
	<% end %>

</ul>